# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3
from deutschland.hochwasserzentralen import api_client, configuration, schemas
from deutschland.hochwasserzentralen.paths.webservices_get_infospegel_php import (  # noqa: E501
    post,
)

from deutschland import hochwasserzentralen

from .. import ApiTestMixin


class TestWebservicesGetInfospegelPhp(ApiTestMixin, unittest.TestCase):
    """
    WebservicesGetInfospegelPhp unit test stubs
        Infos zu einem Pegel.  # noqa: E501
    """

    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200


if __name__ == "__main__":
    unittest.main()
