# coding: utf-8

"""
    hochwasserzentralen.de API

    Das Länderübergreifendes Hochwasserportal (LHP) bietet auf https://www.hochwasserzentralen.de über die hier dokumentierte API Informationen zur Hochwassersituation in Deutschland an. Betreiber des LHP sind das Bayerische Landesamt für Umwelt (LfU) und die Landesanstalt für Umwelt Baden-Württemberg (LUBW). Die Urheberrechte an den veröffentlichten Daten liegen nach [Auskunft der Betreiber](https://www.hochwasserzentralen.de/impressum) bei der für das jeweilige Bundesland zuständigen Hochwasserzentrale bzw. beim jeweiligen Pegelbetreiber.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

from deutschland.hochwasserzentralen.paths.vhosts_geojson_bundesland_version_geojson.get import (
    GetBundeslandGeojson,
)
from deutschland.hochwasserzentralen.paths.webservices_get_infosbundesland_php.get import (
    GetAllBundeslandInfos,
)
from deutschland.hochwasserzentralen.paths.webservices_get_infosbundesland_php.post import (
    GetBundeslandInfosByBundesland,
)


class BundeslandApi(
    GetAllBundeslandInfos,
    GetBundeslandGeojson,
    GetBundeslandInfosByBundesland,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    pass
