"""
    hochwasserzentralen.de API

    Das Länderübergreifendes Hochwasserportal (LHP) bietet auf https://www.hochwasserzentralen.de über die hier dokumentierte API Informationen zur Hochwassersituation in Deutschland an. Betreiber des LHP sind das Bayerische Landesamt für Umwelt (LfU) und die Landesanstalt für Umwelt Baden-Württemberg (LUBW). Die Urheberrechte an den veröffentlichten Daten liegen nach [Auskunft der Betreiber](https://www.hochwasserzentralen.de/impressum) bei der für das jeweilige Bundesland zuständigen Hochwasserzentrale bzw. beim jeweiligen Pegelbetreiber.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.hochwasserzentralen.api.pegel_api import PegelApi  # noqa: E501

from deutschland import hochwasserzentralen


class TestPegelApi(unittest.TestCase):
    """PegelApi unit test stubs"""

    def setUp(self):
        self.api = PegelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_lage_pegel(self):
        """Test case for get_all_lage_pegel

        Lage der Pegel mit Pegelnummern  # noqa: E501
        """
        pass

    def test_get_pegel_infos_by_pegelnummer(self):
        """Test case for get_pegel_infos_by_pegelnummer

        Infos zu einem Pegel.  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
