"""
    hochwasserzentralen.de API

    Das Länderübergreifendes Hochwasserportal (LHP) bietet auf https://www.hochwasserzentralen.de über die hier dokumentierte API Informationen zur Hochwassersituation in Deutschland an. Betreiber des LHP sind das Bayerische Landesamt für Umwelt (LfU) und die Landesanstalt für Umwelt Baden-Württemberg (LUBW). Die Urheberrechte an den veröffentlichten Daten liegen nach [Auskunft der Betreiber](https://www.hochwasserzentralen.de/impressum) bei der für das jeweilige Bundesland zuständigen Hochwasserzentrale bzw. beim jeweiligen Pegelbetreiber.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.hochwasserzentralen.model.bundesland_geojson_inner_fetures_inner_geometry import (
    BundeslandGeojsonInnerFeturesInnerGeometry,
)
from deutschland.hochwasserzentralen.model.bundesland_geojson_inner_fetures_inner_properties import (
    BundeslandGeojsonInnerFeturesInnerProperties,
)

from deutschland import hochwasserzentralen

globals()[
    "BundeslandGeojsonInnerFeturesInnerGeometry"
] = BundeslandGeojsonInnerFeturesInnerGeometry
globals()[
    "BundeslandGeojsonInnerFeturesInnerProperties"
] = BundeslandGeojsonInnerFeturesInnerProperties
from deutschland.hochwasserzentralen.model.bundesland_geojson_inner_fetures_inner import (
    BundeslandGeojsonInnerFeturesInner,
)


class TestBundeslandGeojsonInnerFeturesInner(unittest.TestCase):
    """BundeslandGeojsonInnerFeturesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBundeslandGeojsonInnerFeturesInner(self):
        """Test BundeslandGeojsonInnerFeturesInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BundeslandGeojsonInnerFeturesInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
