"""
    hochwasserzentralen.de API

    Das Länderübergreifendes Hochwasserportal (LHP) bietet auf https://www.hochwasserzentralen.de über die hier dokumentierte API Informationen zur Hochwassersituation in Deutschland an. Betreiber des LHP sind das Bayerische Landesamt für Umwelt (LfU) und die Landesanstalt für Umwelt Baden-Württemberg (LUBW). Die Urheberrechte an den veröffentlichten Daten liegen nach [Auskunft der Betreiber](https://www.hochwasserzentralen.de/impressum) bei der für das jeweilige Bundesland zuständigen Hochwasserzentrale bzw. beim jeweiligen Pegelbetreiber.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.hochwasserzentralen.model.bundesland_geojson_fetures_inner_geometry import (
    BundeslandGeojsonFeturesInnerGeometry,
)

from deutschland import hochwasserzentralen


class TestBundeslandGeojsonFeturesInnerGeometry(unittest.TestCase):
    """BundeslandGeojsonFeturesInnerGeometry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBundeslandGeojsonFeturesInnerGeometry(self):
        """Test BundeslandGeojsonFeturesInnerGeometry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BundeslandGeojsonFeturesInnerGeometry()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
