"""
    hochwasserzentralen.de API

    Das Länderübergreifendes Hochwasserportal (LHP) bietet auf https://www.hochwasserzentralen.de über die hier dokumentierte API Informationen zur Hochwassersituation in Deutschland an. Betreiber des LHP sind das Bayerische Landesamt für Umwelt (LfU) und die Landesanstalt für Umwelt Baden-Württemberg (LUBW). Die Urheberrechte an den veröffentlichten Daten liegen nach [Auskunft der Betreiber](https://www.hochwasserzentralen.de/impressum) bei der für das jeweilige Bundesland zuständigen Hochwasserzentrale bzw. beim jeweiligen Pegelbetreiber.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.hochwasserzentralen.api.bundesland_api import (  # noqa: E501
    BundeslandApi,
)

from deutschland import hochwasserzentralen


class TestBundeslandApi(unittest.TestCase):
    """BundeslandApi unit test stubs"""

    def setUp(self):
        self.api = BundeslandApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_bundesland_infos(self):
        """Test case for get_all_bundesland_infos

        Infos zu allen Bundesländern und angeschlossen Gebieten.  # noqa: E501
        """
        pass

    def test_get_bundesland_geojson(self):
        """Test case for get_bundesland_geojson

        Geojson der Bundesländer  # noqa: E501
        """
        pass

    def test_get_bundesland_infos_by_bundesland(self):
        """Test case for get_bundesland_infos_by_bundesland

        Infos zu einem Bundesland.  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
