"""
    hochwasserzentralen.de API

    Das Länderübergreifendes Hochwasserportal (LHP) bietet auf https://www.hochwasserzentralen.de über die hier dokumentierte API Informationen zur Hochwassersituation in Deutschland an. Betreiber des LHP sind das Bayerische Landesamt für Umwelt (LfU) und die Landesanstalt für Umwelt Baden-Württemberg (LUBW). Die Urheberrechte an den veröffentlichten Daten liegen nach [Auskunft der Betreiber](https://www.hochwasserzentralen.de/impressum) bei der für das jeweilige Bundesland zuständigen Hochwasserzentrale bzw. beim jeweiligen Pegelbetreiber.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.hochwasserzentralen.model.bundesland_geojson_inner import (
    BundeslandGeojsonInner,
)

from deutschland import hochwasserzentralen

globals()["BundeslandGeojsonInner"] = BundeslandGeojsonInner
from deutschland.hochwasserzentralen.model.bundesland_geojson import BundeslandGeojson


class TestBundeslandGeojson(unittest.TestCase):
    """BundeslandGeojson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBundeslandGeojson(self):
        """Test BundeslandGeojson"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BundeslandGeojson()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
